<style scoped>

.about-text {
    font-size: 18px;
    color: #212322;
    text-align: justify;
}

h3 {
    font-family: "Open Sans", sans-serif;
    font-size: 30px;
    font-weight: bold;
}

p {
    font-family: "Inconsolata", monospace;
}

</style>

<template>

<div>
    <MenuBar/>
    <b-row class="about-text" align-h="center">
        <b-col cols="10">
            <h3>About the project</h3>
            <p class="about-text">
                I'm Alice. This website is part of my graduation project for the Master of Arts in Fine Art and Design: Experimental Publishing, in which I question the role of technology in the development of innovative food. More specifically, I'm deconstructing what
                I've identified as the meal-replacement phenomenon, an ideology, culture, community and, ultimately, range of products that have emerged out of Silicon Valley's techno-solutionism approach to problem solving in the past 5 years, and have
                spread out across the Western world.
            </p>
            <p>
                In my research, I've taken a closer look at the culture of quick-fixes for complex problems, and the role of meal replacements within societies which value the authoritative roles of tech innovators and their potential to impact the way humans live. I've
                also engaged with the communities and individuals who find comfort and reassurance in these quick-fixes, while sometimes struggling with much deeper issues. I've embodied my research by the means of changing my diet, I've had countless
                discussions with people both outraged and excited, and found that my research topic leaves no one untouched. Food is a highly personal, culturally charged and omnipresent topic in our lives, and challenging its fundamental role, as well as our values and priorities, is always bound to
                trigger a reaction.
            </p>
            <p>The industry of meal replacements has grown alongside the communities around it. And here it became most obvious to me that nothing has a bigger impact on this range of products than the reviews generated by their consumers. Reviews are shared and discussed, requested and challenged on social platforms like YouTube, Instagram and Reddit, and the brands are not only listening, but chiming in. With my work, I want to contribute to this pool of reviews by adding another layer, by reviewing the culture itself and all of its implications. </p>

        </b-col>
    </b-row>

    <b-row align-h="center">
        <b-col cols="10">
            <h3>About the essay</h3>
            <p class="about-text">
                "Your Body Will Make Itself Heard" represents my masters' thesis, and takes a broader look at the historical, cultural and technological development of meal replacements.
            </p>
        </b-col>
    </b-row>

    <b-row class="about-text" align-h="center">
        <b-col cols="10">
            <h3>About the video</h3>
            <p class="about-text">
                "Is It Time to Eat, Or Is There No More Time to Eat" is a short desktop film that complements my research on meal replacements. As opposed to a broader look on the topic, the video focuses on the issue of solving problems through the means of techno-solutionism.
                It's built in the form of a vlog which responds to and exists in the same space as the body of reviews, unboxing and tasting videos that exist within the culture of meal replacements.
            </p>
        </b-col>
    </b-row>

</div>

</template>

<script>

import MenuBar from './MenuBar'
export default {
    name: 'AboutPage',
    components: {
        MenuBar
    }
}

</script>
